apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-public1
spec:
  replicas: 1
  selector:
    matchLabels:
      application: http-server
  template:
    metadata:
      labels:
        application: http-server
    spec:
      containers:
      - name: server
        env:
        - name: SKUPPER_EXAMPLE_LATENCY
          value: "10"
        image: quay.io/skupper/skupper-http-server
        imagePullPolicy: IfNotPresent
